equinox not compatible with numpyro maybe need flax or haiku
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpyro\primitives.py:400, in module(name, nn, input_shape)
    385 """
    386 Declare a :mod:`~jax.example_libraries.stax` style neural network inside a
    387 model so that its parameters are registered for optimization via
   (...)
    397     array.
    398 """
    399 module_key = name + "$params"
--> 400 nn_init, nn_apply = nn
    401 nn_params = param(module_key)
    402 if nn_params is None:

TypeError: cannot unpack non-iterable NeuralODE object